#!/bin/sh
# Emit an assembly symbol table (address-sorted text symbols) for panics.
#   gen-ksyms.sh <nm> <kernel.elf>
NM=$1; ELF=$2
echo '/* generated by scripts/gen-ksyms.sh — do not edit */'
echo '    .section .rodata.ksyms, "a"'
echo '    .balign 8'
echo '    .globl ksyms_table'
echo 'ksyms_table:'
$NM -n --defined-only "$ELF" | awk '$2 ~ /^[tTwW]$/ { printf "    .quad 0x%s, .Lsym%d\n", $1, n++ } END { print "    .globl ksyms_count"; print "    .balign 8"; print "ksyms_count:"; printf "    .quad %d\n", n }'
echo '    .section .rodata.ksyms_str, "a"'
$NM -n --defined-only "$ELF" | awk '$2 ~ /^[tTwW]$/ { printf ".Lsym%d: .asciz \"%s\"\n", n++, $3 }'
