#!/usr/bin/env python3
"""Convert a BDF bitmap font into a C array of 256 glyphs (CP437-style layout).

ASCII / Latin-1 code points map to themselves; the Unicode block and
box-drawing characters used by the UI are placed at their CP437 slots.

Usage: bdf2c.py font.bdf WIDTH HEIGHT symbol > out.c
"""
import sys

CP437 = {0x2588: 0xDB, 0x2591: 0xB0, 0x2592: 0xB1, 0x2593: 0xB2, 0x2500: 0xC4,
         0x2502: 0xB3, 0x250C: 0xDA, 0x2510: 0xBF, 0x2514: 0xC0, 0x2518: 0xD9,
         0x25B2: 0x1E, 0x25BC: 0x1F, 0x25B6: 0x10, 0x25C0: 0x11, 0x2022: 0x07}


def main():
    path, W, H, sym = sys.argv[1], int(sys.argv[2]), int(sys.argv[3]), sys.argv[4]
    glyphs, cur, bitmap, in_bm, bbx, fbb_y = {}, None, [], False, None, 0
    for line in open(path, encoding="latin-1"):
        p = line.split()
        if not p:
            continue
        if p[0] == "FONTBOUNDINGBOX":
            fbb_y = int(p[4])            # usually negative: descent
        elif p[0] == "ENCODING":
            cur = int(p[1])
        elif p[0] == "BBX":
            bbx = list(map(int, p[1:5]))
        elif p[0] == "BITMAP":
            in_bm, bitmap = True, []
        elif p[0] == "ENDCHAR":
            in_bm = False
            if cur in CP437:
                slot = CP437[cur]
            elif 0x20 <= cur < 0x7f or 0xa0 <= cur < 0x100:
                slot = cur
            else:
                continue
            w, h, xo, yo = bbx
            rows = [0] * H
            # Cell rows run top→bottom; the baseline sits at H + fbb_y from the top.
            for i, hexrow in enumerate(bitmap):
                v = int(hexrow, 16) >> (len(hexrow) * 4 - w)
                y = (H + fbb_y) - (yo + h) + i
                shift = W - w - xo
                if 0 <= y < H:
                    rows[y] = (v << shift) if shift >= 0 else (v >> -shift)
            glyphs[slot] = rows
        elif in_bm:
            bitmap.append(p[0])

    bpr = (W + 7) // 8
    ctype = {1: "uint8_t", 2: "uint16_t"}[bpr]
    print(f"/* Generated by tools/bdf2c.py from {path.split('/')[-1]}")
    print(" * Spleen font, BSD-2-Clause, (c) Frederic Cambus — see FONT-LICENSE.spleen. */")
    print("#include <stdint.h>")
    print(f"const {ctype} {sym}[256][{H}] = {{")
    for c in range(256):
        rows = glyphs.get(c, [0] * H)
        print("\t{" + ",".join(f"0x{r:0{bpr * 2}x}" for r in rows) + f"}}, /* {c:#04x} */")
    print("};")


if __name__ == "__main__":
    main()
