"""Convert logo.png (white "FUHRER" + red "OS" on black) into kernel/gfx/logo.c.

The wordmark is stored as two 8-bit alpha masks per size: `fg` (the white
letters) and `accent` (the red letters). The compositor tints them at draw
time (fg = theme text colour, accent = theme accent), so the logo works on
dark and light themes. Run on a host with Pillow:  python tools/logo2c.py
"""
import os
from PIL import Image

ROOT = os.path.join(os.path.dirname(__file__), "..")
HEIGHTS = [12, 16, 24, 40, 64]      # panel, small, launcher, lock, wallpaper/splash

im = Image.open(os.path.join(ROOT, "logo.png")).convert("RGB")
px = im.load()
w, h = im.size
# bounding box of the lit pixels
xs, ys = [], []
for y in range(h):
    for x in range(w):
        if max(px[x, y]) > 60:
            xs.append(x)
            ys.append(y)
box = (min(xs), min(ys), max(xs) + 1, max(ys) + 1)
crop = im.crop(box)
cw, ch = crop.size
fg = Image.new("L", crop.size)
ac = Image.new("L", crop.size)
cp, fp, ap = crop.load(), fg.load(), ac.load()
for y in range(ch):
    for x in range(cw):
        r, g, b = cp[x, y]
        red = max(0, r - max(g, b))          # saturated red part
        white = min(r, g, b)                 # neutral (white/grey) part
        ap[x, y] = min(255, red * 255 // 230)
        fp[x, y] = min(255, white * 255 // 235)

out = ["/* Generated by tools/logo2c.py from logo.png - do not edit. */",
       '#include "gfx/fb.h"', ""]
entries = []
for H in HEIGHTS:
    W = round(cw * H / ch)
    for name, plane in (("fg", fg), ("ac", ac)):
        data = plane.resize((W, H), Image.LANCZOS).tobytes()
        out.append(f"static const u8 logo{H}_{name}[{W * H}] = {{")
        for i in range(0, len(data), 24):
            out.append("\t" + ", ".join(str(b) for b in data[i:i + 24]) + ",")
        out.append("};")
    entries.append(f"\t{{ {W}, {H}, logo{H}_fg, logo{H}_ac }},")
out += ["", "const struct logo_image logo_images[] = {"] + entries + ["};",
        f"const int logo_image_count = {len(HEIGHTS)};", ""]
dst = os.path.join(ROOT, "kernel", "gfx", "logo.c")
open(dst, "w", newline="\n").write("\n".join(out))
print("wrote", dst, "crop", box, "sizes", [(round(cw * H / ch), H) for H in HEIGHTS])
